/******************************************************************************
*  Generated by PSoC Designer 5.3.2710
******************************************************************************/
#include <m8c.h>
// Bit0 address and mask defines
#pragma	ioport	Bit0_Data_ADDR:	0x4
BYTE			Bit0_Data_ADDR;
#pragma	ioport	Bit0_DriveMode_0_ADDR:	0x104
BYTE			Bit0_DriveMode_0_ADDR;
#pragma	ioport	Bit0_DriveMode_1_ADDR:	0x105
BYTE			Bit0_DriveMode_1_ADDR;
#pragma	ioport	Bit0_DriveMode_2_ADDR:	0x7
BYTE			Bit0_DriveMode_2_ADDR;
#pragma	ioport	Bit0_GlobalSelect_ADDR:	0x6
BYTE			Bit0_GlobalSelect_ADDR;
#pragma	ioport	Bit0_IntCtrl_0_ADDR:	0x106
BYTE			Bit0_IntCtrl_0_ADDR;
#pragma	ioport	Bit0_IntCtrl_1_ADDR:	0x107
BYTE			Bit0_IntCtrl_1_ADDR;
#pragma	ioport	Bit0_IntEn_ADDR:	0x5
BYTE			Bit0_IntEn_ADDR;
#define Bit0_MASK 0x1
// Bit1 address and mask defines
#pragma	ioport	Bit1_Data_ADDR:	0x4
BYTE			Bit1_Data_ADDR;
#pragma	ioport	Bit1_DriveMode_0_ADDR:	0x104
BYTE			Bit1_DriveMode_0_ADDR;
#pragma	ioport	Bit1_DriveMode_1_ADDR:	0x105
BYTE			Bit1_DriveMode_1_ADDR;
#pragma	ioport	Bit1_DriveMode_2_ADDR:	0x7
BYTE			Bit1_DriveMode_2_ADDR;
#pragma	ioport	Bit1_GlobalSelect_ADDR:	0x6
BYTE			Bit1_GlobalSelect_ADDR;
#pragma	ioport	Bit1_IntCtrl_0_ADDR:	0x106
BYTE			Bit1_IntCtrl_0_ADDR;
#pragma	ioport	Bit1_IntCtrl_1_ADDR:	0x107
BYTE			Bit1_IntCtrl_1_ADDR;
#pragma	ioport	Bit1_IntEn_ADDR:	0x5
BYTE			Bit1_IntEn_ADDR;
#define Bit1_MASK 0x2
// Bit2 address and mask defines
#pragma	ioport	Bit2_Data_ADDR:	0x4
BYTE			Bit2_Data_ADDR;
#pragma	ioport	Bit2_DriveMode_0_ADDR:	0x104
BYTE			Bit2_DriveMode_0_ADDR;
#pragma	ioport	Bit2_DriveMode_1_ADDR:	0x105
BYTE			Bit2_DriveMode_1_ADDR;
#pragma	ioport	Bit2_DriveMode_2_ADDR:	0x7
BYTE			Bit2_DriveMode_2_ADDR;
#pragma	ioport	Bit2_GlobalSelect_ADDR:	0x6
BYTE			Bit2_GlobalSelect_ADDR;
#pragma	ioport	Bit2_IntCtrl_0_ADDR:	0x106
BYTE			Bit2_IntCtrl_0_ADDR;
#pragma	ioport	Bit2_IntCtrl_1_ADDR:	0x107
BYTE			Bit2_IntCtrl_1_ADDR;
#pragma	ioport	Bit2_IntEn_ADDR:	0x5
BYTE			Bit2_IntEn_ADDR;
#define Bit2_MASK 0x4
// Bit3 address and mask defines
#pragma	ioport	Bit3_Data_ADDR:	0x4
BYTE			Bit3_Data_ADDR;
#pragma	ioport	Bit3_DriveMode_0_ADDR:	0x104
BYTE			Bit3_DriveMode_0_ADDR;
#pragma	ioport	Bit3_DriveMode_1_ADDR:	0x105
BYTE			Bit3_DriveMode_1_ADDR;
#pragma	ioport	Bit3_DriveMode_2_ADDR:	0x7
BYTE			Bit3_DriveMode_2_ADDR;
#pragma	ioport	Bit3_GlobalSelect_ADDR:	0x6
BYTE			Bit3_GlobalSelect_ADDR;
#pragma	ioport	Bit3_IntCtrl_0_ADDR:	0x106
BYTE			Bit3_IntCtrl_0_ADDR;
#pragma	ioport	Bit3_IntCtrl_1_ADDR:	0x107
BYTE			Bit3_IntCtrl_1_ADDR;
#pragma	ioport	Bit3_IntEn_ADDR:	0x5
BYTE			Bit3_IntEn_ADDR;
#define Bit3_MASK 0x8
// Bit4 address and mask defines
#pragma	ioport	Bit4_Data_ADDR:	0x4
BYTE			Bit4_Data_ADDR;
#pragma	ioport	Bit4_DriveMode_0_ADDR:	0x104
BYTE			Bit4_DriveMode_0_ADDR;
#pragma	ioport	Bit4_DriveMode_1_ADDR:	0x105
BYTE			Bit4_DriveMode_1_ADDR;
#pragma	ioport	Bit4_DriveMode_2_ADDR:	0x7
BYTE			Bit4_DriveMode_2_ADDR;
#pragma	ioport	Bit4_GlobalSelect_ADDR:	0x6
BYTE			Bit4_GlobalSelect_ADDR;
#pragma	ioport	Bit4_IntCtrl_0_ADDR:	0x106
BYTE			Bit4_IntCtrl_0_ADDR;
#pragma	ioport	Bit4_IntCtrl_1_ADDR:	0x107
BYTE			Bit4_IntCtrl_1_ADDR;
#pragma	ioport	Bit4_IntEn_ADDR:	0x5
BYTE			Bit4_IntEn_ADDR;
#define Bit4_MASK 0x10
// Bit5 address and mask defines
#pragma	ioport	Bit5_Data_ADDR:	0x4
BYTE			Bit5_Data_ADDR;
#pragma	ioport	Bit5_DriveMode_0_ADDR:	0x104
BYTE			Bit5_DriveMode_0_ADDR;
#pragma	ioport	Bit5_DriveMode_1_ADDR:	0x105
BYTE			Bit5_DriveMode_1_ADDR;
#pragma	ioport	Bit5_DriveMode_2_ADDR:	0x7
BYTE			Bit5_DriveMode_2_ADDR;
#pragma	ioport	Bit5_GlobalSelect_ADDR:	0x6
BYTE			Bit5_GlobalSelect_ADDR;
#pragma	ioport	Bit5_IntCtrl_0_ADDR:	0x106
BYTE			Bit5_IntCtrl_0_ADDR;
#pragma	ioport	Bit5_IntCtrl_1_ADDR:	0x107
BYTE			Bit5_IntCtrl_1_ADDR;
#pragma	ioport	Bit5_IntEn_ADDR:	0x5
BYTE			Bit5_IntEn_ADDR;
#define Bit5_MASK 0x20
// Bit6 address and mask defines
#pragma	ioport	Bit6_Data_ADDR:	0x4
BYTE			Bit6_Data_ADDR;
#pragma	ioport	Bit6_DriveMode_0_ADDR:	0x104
BYTE			Bit6_DriveMode_0_ADDR;
#pragma	ioport	Bit6_DriveMode_1_ADDR:	0x105
BYTE			Bit6_DriveMode_1_ADDR;
#pragma	ioport	Bit6_DriveMode_2_ADDR:	0x7
BYTE			Bit6_DriveMode_2_ADDR;
#pragma	ioport	Bit6_GlobalSelect_ADDR:	0x6
BYTE			Bit6_GlobalSelect_ADDR;
#pragma	ioport	Bit6_IntCtrl_0_ADDR:	0x106
BYTE			Bit6_IntCtrl_0_ADDR;
#pragma	ioport	Bit6_IntCtrl_1_ADDR:	0x107
BYTE			Bit6_IntCtrl_1_ADDR;
#pragma	ioport	Bit6_IntEn_ADDR:	0x5
BYTE			Bit6_IntEn_ADDR;
#define Bit6_MASK 0x40
// Bit7 address and mask defines
#pragma	ioport	Bit7_Data_ADDR:	0x4
BYTE			Bit7_Data_ADDR;
#pragma	ioport	Bit7_DriveMode_0_ADDR:	0x104
BYTE			Bit7_DriveMode_0_ADDR;
#pragma	ioport	Bit7_DriveMode_1_ADDR:	0x105
BYTE			Bit7_DriveMode_1_ADDR;
#pragma	ioport	Bit7_DriveMode_2_ADDR:	0x7
BYTE			Bit7_DriveMode_2_ADDR;
#pragma	ioport	Bit7_GlobalSelect_ADDR:	0x6
BYTE			Bit7_GlobalSelect_ADDR;
#pragma	ioport	Bit7_IntCtrl_0_ADDR:	0x106
BYTE			Bit7_IntCtrl_0_ADDR;
#pragma	ioport	Bit7_IntCtrl_1_ADDR:	0x107
BYTE			Bit7_IntCtrl_1_ADDR;
#pragma	ioport	Bit7_IntEn_ADDR:	0x5
BYTE			Bit7_IntEn_ADDR;
#define Bit7_MASK 0x80
